version: '3'

services:
  pero-ocr-api:
    build: ./services/CL_pero_ocr
    image: docker.crosslang.com/occam/pero-ocr-api
    ports:
      - 9065:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
