version: '3'

services:
  django:
    build:
      ./backend
    env_file:
      - ./secrets/ocr.env
### We already copy the folder. Also, ./start.sh can't be run from volume mapping.
#    volumes:
#      - ./backend:/backend
    command: ./start.sh
    restart:
      always
    ports:
      - "9060:8000"
