FROM pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime

RUN apt-get update && apt-get install -y python3-opencv

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

# PERO-OCR - release 0.6.1
RUN pip3 install pero-ocr==0.6.1

COPY ./requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

WORKDIR "/app"

# TODO remove reload in deployment
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload", "--port", "80"]
