# Generated by Django 3.0.5 on 2020-07-06 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('folder', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LayOutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('layout_model', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OCRModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('ocr_model', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OCRImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr', to='pero_ocr_app.ImageFile')),
                ('layout_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr', to='pero_ocr_app.LayOutModel')),
                ('ocr_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr', to='pero_ocr_app.OCRModel')),
            ],
        ),
    ]
