# Generated by Django 3.0.5 on 2020-07-06 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pero_ocr_app', '0002_auto_20200706_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrimage',
            name='layout_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr', to='pero_ocr_app.LayoutModel'),
        ),
    ]
