# Generated by Django 3.0.5 on 2020-07-07 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pero_ocr_app', '0004_auto_20200706_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrimage',
            name='layout_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr', to='pero_ocr_app.LayoutModel'),
        ),
        migrations.CreateModel(
            name='OCRFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocrfolder', to='pero_ocr_app.ImageFolder')),
                ('layout_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocrfolder', to='pero_ocr_app.LayoutModel')),
                ('ocr_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocrfolder', to='pero_ocr_app.OCRModel')),
            ],
        ),
    ]
